---
title: "Accessing SL Provided Social Science Data with R"
author: 'Online at: bit.ly/sul-db-R'
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')` --  cengel @ stanford"
output: pdf_document
---

The Stanford Libraries (SL) offer a number of datasets for social science research. This is a document detailing if and how those can be accessed when using R. It is work in progress. ([Download as pdf.](https://github.com/cengel/cengel.github.io/raw/master/gearup2016/SULdataAccess.pdf))


## Data from SL

- [Bloomberg](http://www.bloomberg.com) 
    - Restricted to designated machines at GSB
    - Details here: http://libguides.stanford.edu/bloomberg

- [Bureau of Economic Analysis](http://www.bea.gov)
    - [has API](http://www.bea.gov/API/docs/index.htm)
    - R package [announced for late Oct 2016](https://blog.bea.gov/2016/09/28/guest-blog-white-house-open-data-innovation-summit/)

- [California Attorney General’s Open Justice Portal](http://openjustice.doj.ca.gov/index.html) 
    - Use `read.csv(url("http:..."))` to load _CSV_ from [their data portal](http://openjustice.doj.ca.gov/data).  
  
- [Census public/RDC](http://www.census.gov)   
    - Public census [has APIs](http://www.census.gov/data/developers/data-sets.html) 
    - RDC restricted to designated, offline machines
    - R packages: 
        - [acs](https://cran.r-project.org/package=acs) (some instructions [here](http://eglenn.scripts.mit.edu/citystate/wp-content/uploads/2013/06/wpid-working_with_acs_R3.pdf))
        - [UScensus2010](https://cran.r-project.org/package=UScensus2010)
        - [tigris](https://cran.r-project.org/package=tigris)
        - [tidycensus](https://CRAN.R-project.org/package=tidycensus): Loads US Census boundary and attribute data as `tidyverse` and `sf`-ready data frames
        - [censusapi](https://CRAN.R-project.org/package=censusapi): A wrapper for the US Census Bureau APIs that returns data frames of Census data and metadata.
        - [idbr](https://CRAN.R-project.org/package=idbr): US Census Bureau's International Data Base
    - References, slighty outdated: 
        - [Getting data from the ACS into R](http://spatialdemography.org/wp-content/uploads/2013/04/9.-Sparks.pdf)
        - [Performing spatial regression modeling in R with ACS data](http://spatialdemography.org/wp-content/uploads/2013/10/6.-Sparks.pdf)

- [CoreLogic](http://www.corelogic.com) 
    - Stanford only, download _XLS_ [from Stanford Digital Repository](https://purl.stanford.edu/pv311by5369) 
    - **need to read and sign End User License Agreement before use**

- [DataPlanet](http://data-planet.com)  
    - Stanford only via [EzProxy](http://statisticaldatasets.data-planet.com.ezproxy.stanford.edu/dataplanet/Datasets.html) and export _CSV_
    - Supposedly [has API(?)](http://homepage.data-planet.com/content-syndication), but [request form is not accessible](http://homepage.data-planet.com/request-form) 

- [Gallup Analytics](http://www.gallup.com/)  
    - Stanford only, via [EzProxy](https://analyticscampus-gallup-com.ezproxy.stanford.edu/) 
    - Data download through web interface as _XLSX_ only -- **broken or disabled(?)**
    
- [ICPSR](http://icpsr.umich.edu/) 
    - R package [`icpsrdata`](https://cran.r-project.org/package=icpsrdata) [(GitHub)](https://github.com/fsolt/icpsrdata)  

- [IMF](http://data.imf.org/) 
    - [Has API](http://datahelp.imf.org/knowledgebase/articles/630877-api) 
    - R packages:
        - [`IMFData`](https://cran.r-project.org/package=IMFData) [(GitHub)](https://github.com/mingjerli/IMFData) 
        - [`rWEO`](https://github.com/mingjerli/rWEO) for IMF-WEO data 
    
- [IPUMS](https://www.ipums.org/)
    - R package [`ipumsr`](https://cran.r-project.org/package=ipumsr) to import census, survey and geographic data provided by IPUMS into R. Great [vignette](https://cran.rstudio.com/web/packages/ipumsr/vignettes/ipums.html), also for [Value labels](https://cran.rstudio.com/web/packages/ipumsr/vignettes/value-labels.html), [Current Population Survey (CPS)](https://cran.rstudio.com/web/packages/ipumsr/vignettes/ipums-cps.html), [Geographic Data](https://cran.rstudio.com/web/packages/ipumsr/vignettes/ipums-geography.html), and [use of NHGIS](https://cran.rstudio.com/web/packages/ipumsr/vignettes/ipums-nhgis.html).

- [MapLight](http://maplight.org/data) 
    - [Bill Positions](http://maplight.org/apis/bill-positions) has [API](http://maplight.org/services_open_api) 
    - [Some R code from Hadley Wickham](https://github.com/hadley/maplight-data) (not a package!). Last commit several years back, but still seems to work.
    - Download [California Money and Politics Bulk Data Set](http://maplight.org/data/get/california-money-and-politics-dataset) and [Federal Money and Politics Data Set](http://maplight.org/data/get/federal-money-and-politics-dataset) as zipped _CSV_, like [this](http://stackoverflow.com/a/3053883/2630957).

- [OECD](https://www.oecd.org/) 
    - R package [`OECD`](https://cran.r-project.org/package=OECD) [(GitHub)](https://github.com/expersso/OECD)

- [ProQuest Statistical Products](http://statistical.proquest.com)
    - Stanford only, via [EzProxy](http://statistical.proquest.com.ezproxy.stanford.edu/)
    - Data download as _XLS_ (or _PDF_)

- [RefUSA](http://www.referenceusa.com)
    - Stanford only, via [GSB](http://www.referenceusa.com.gsbproxy.stanford.edu)
    - Data download as _CSV_, _TSV_, _Excel_ (275 downloads per search)
    
- [Roper iPoll](http://ropercenter.cornell.edu/ipoll-database/)
    - Stanford only, via [EzProxy](https://ropercenter-cornell-edu.ezproxy.stanford.edu/CFIDE/cf/action/ipoll/index.cfm)
    - Data download seems tedious. I was only able to download _CSV_ for a single question at a time. 

- [San Mateo County Open Data](https://data.smcgov.org) 
    - Use generic [Socrata Open Data API](https://dev.socrata.com/connectors/rsocrata.html) 
    - R package [`RSocrata`](https://cran.r-project.org/package=RSocrata) [(GitHub)](https://github.com/Chicago/RSocrata) 

- [PolicyMap](https://www.policymap.com)
    - Stanford access via https://stanford.policymap.com/ -- need to be either on campus, or use VPN or set up browser proxy. 5 concurrent licenses.
    - Manual data download, no remote access (guest account allows to download _CSV_, Stanford access allows to download _SHP_ as well)

- [World Bank](http://data.worldbank.org)  
    - Currently [60 databases](http://databank.worldbank.org/data/databases.aspx)
    - [Has API](https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information)
    - R packages: 
        - [`WDI`](https://cran.r-project.org/package=WDI) [(GitHub)](https://github.com/vincentarelbundock/WDI)
        - [`wbstats`](https://cran.r-project.org/package=wbstats)
        - [`rWBData`](https://github.com/mingjerli/rWBData)
        - [`rWBclimate`](https://github.com/ropensci/rWBclimate) for the World Bank climate data
    
- [Wharton Research Data Services](https://wrds-web.wharton.upenn.edu/wrds/) (WRDS)  
    - Stanford login via [GSB](http://wrds-web.wharton.upenn.edu.gsbproxy.stanford.edu/wrds/connect/)
    - Data access via remote connection to SAS/SHARE server, which allows direct query of WRDS data via standard database queries, using their (remote) R version.
    - Documentation: 
        - [WRDS Data Directly from Python, R, and MATLAB](https://research-it.wharton.upenn.edu/news/working-with-wrds-data-directly-from-python-r-and-matlab/)
        - [Using R with WRDS](https://wrds-web-wharton-upenn-edu.gsbproxy.stanford.edu/wrds/support/Accessing%20and%20Manipulating%20the%20Data/_007R%20Programming/_001Using%20R%20with%20WRDS.cfm) 
    - Sparsely documented R package [`wrds`](https://github.com/wthielen/wrds) 

## Other R packages
- US Bureau of Labor Statistics (BLS):
    - [`rUnemploymentData`](https://cran.r-project.org/package=rUnemploymentData)
    - [`blscrapeR`](https://CRAN.R-project.org/package=blscrapeR)
- [DataCite](https://www.datacite.org/):  [`rdatacite`](https://cran.r-project.org/package=rdatacite) 
- Medicare public files: [`medicare`](https://CRAN.R-project.org/package=medicare)
- Social Media for Network Analysis: [`SocialMediaLab`]( https://CRAN.R-project.org/package=SocialMediaLab)
- United States Treasury 
    - [`Rtreasuryio`](https://github.com/csvsoundsystem/Rtreasuryio): a single, simple function for submitting SQL queries to [`treasury.io`](http://treasury.io)
- [`enigma`](https://CRAN.R-project.org/package=enigma): a client to interact with the [Enigma](https://public.enigma.com) API, including getting the data and metadata for datasets as well as collecting statistics on datasets. (Note that there is another site: [Enigma Public](https://public.enigma.com) "the world’s broadest collection of public data" which provides API access as well, not sure how the two are related with regard to this package.)
- [`pdfetch`](https://CRAN.R-project.org/package=pdfetch): Economic and financial time series from public sources, including the St Louis Fed's FRED system, Yahoo Finance, the US Bureau of Labor Statistics, the US Energy Information Administration, the World Bank, Eurostat, the European Central Bank, the Bank of England, the UK's Office of National Statistics, Deutsche Bundesbank, and INSEE.
- [`eechidna`](https://CRAN.R-project.org/package=eechidna): 2013 and 2016 Australian Federal Election (House of Representatives) and the 2011 Australian Census
- [`rtimes`](https://CRAN.R-project.org/package=rtimes): Interface to Congress, Campaign Finance, Article Search, and Geographic APIs from the [New York Times](http://developer.nytimes.com/) and [ProPublica](https://www.propublica.org/datastore/apis). Covers only a subset of the APIs.
- [`crminer`](https://CRAN.R-project.org/package=crminer) and [`rcrossref`](https://CRAN.R-project.org/package=rcrossref): Text mining client for [Crossref](<https://crossref.org>). Includes functions for getting getting links to full text of articles, fetching full text articles from those links or Digital Object Identifiers (DOIs), and text extraction from PDFs. `rcrossref` is for metadata.
- [`rdpla`](https://CRAN.R-project.org/package=rdpla): Client for the [Digital Public Library of America (DPLA)](https://dp.la), using its [REST API](https://dp.la/info/developers/codex/)
- [`internetarchive`](https://CRAN.R-project.org/package=internetarchive): Search the [Internet Archive](https://archive.org/), retrieve metadata, and download files.
- [`patentsview`](https://CRAN.R-project.org/package=patentsview): An R Client for [PatentsView](http://www.patentsview.org) with functions to simplify the [PatentsView API](http://www.patentsview.org/api/doc.html) query language and parse the data that comes back.
- [`pleiades`](https://CRAN.R-project.org/package=pleiades): Interface to the [Pleiades Archeological Database](https://pleiades.stoa.org/)
- [`USAboundaries`](https://CRAN.R-project.org/package=USAboundaries): Historical boundaries of the United States. Map the United States (or the colonies that became the United States) on any date from 1629 to 2000. Contains both county and state/territory level polygons.
- [`rdatacite`](https://CRAN.R-project.org/package=rdatacite) Client for the web service methods provided by [DataCite](https://www.datacite.org/)
- [`roadoi`](https://CRAN.R-project.org/package=roadoi): Find Free Versions of Scholarly Publications via the [oaDOI Service](https://oadoi.org)
- [`data.world`](https://cran.rstudio.com/web/packages/data.world/):  High-level tools for working with [data.world](https://data.world) data sets.
- [`jstor`](https://github.com/tklebel/jstor): Import journal data from DfR (JSTOR)
- [`fulltext`](https://CRAN.R-project.org/package=fulltext): A single interface to full text sources 'scholarly' data, including 'Biomed Central', Public Library of Science, 'Pubmed Central', 'eLife', and more. [(Manual)](https://ropensci.org/technotes/2018/01/17/fulltext-v1/)


(A number of packages are from  https://ropensci.org/. You may want to check there for new ones.)    

